export const PAYMENT_STATUS = Object.freeze({
  CREATED: "CREATED",
  PENDING: "PENDING",
  PENDING_VERIFICATION: "PENDING_VERIFICATION",
  PENDING_REVIEW: "PENDING_REVIEW",
  VERIFIED_PAID: "VERIFIED_PAID",
  FAILED: "FAILED",
  CANCELLED: "CANCELLED",
  EXPIRED: "EXPIRED",
  AMOUNT_MISMATCH: "AMOUNT_MISMATCH",
});

export function isPaidStatus(status) {
  return status === PAYMENT_STATUS.VERIFIED_PAID;
}

export function isTerminalStatus(status) {
  return [
    PAYMENT_STATUS.VERIFIED_PAID,
    PAYMENT_STATUS.FAILED,
    PAYMENT_STATUS.CANCELLED,
    PAYMENT_STATUS.EXPIRED,
    PAYMENT_STATUS.AMOUNT_MISMATCH,
  ].includes(status);
}
